#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=slurm_output/slurm_output_%A.out


module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment
source activate py27

# Run your code
srun python -u launcher.py --exp_type=test --simu_len=50 --num_ex=15 --pg_re=train/DeepRM_2/simu50,numex15,epoch31/pg_re_30.pkl --unseen=True --use_cnn=True --ofile=data/test

# srun python -u launcher.py --exp_type=test --simu_len=5 --num_ex=5 --pg_re=experiments/DeepRM_ECO/simu5,numex5,epoch51/pg_re_50.pkl --unseen=True --use_cnn=False --ofile=data/test

