#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=slurm_output/slurm_output_%A.out


module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment
source activate py27

# start simu_len
start_len=50

# end simu_len
end_len=190

# increment step
increment=10

for (( simu_len=$start_len; simu_len<=$end_len; simu_len+=$increment ))
do
    python launcher.py --exp_type=test --simu_len=$simu_len --num_ex=20 --pg_re=train/DeepRM_ECO/simu30,numex15,epoch101/pg_re_100.pkl --unseen=True --use_cnn=False
done